### ISSUE TITLE
##[error]Found no pull request.

### ISSUE THREAD

**Issue by revmischa** [5monkeys/cobertura-action#10]
```yaml
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v2
      - name: Restore target dir
        uses: actions/download-artifact@v1
        with:
          name: target
      - name: Coverage
        uses: jetbridge/github-action-sbt@11-1.3.0-2.13.0-p2
        with:
          commands: coverage coverageReport
      - uses: 5monkeys/cobertura-action@master
        with:
          path: target/scala-2.12/coverage-report/cobertura.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 90
```

Gives me the error:
```
Run 5monkeys/cobertura-action@master
  with:
    path: target/scala-2.12/coverage-report/cobertura.xml
    repo_token: ***
    minimum_coverage: 90
    skip_covered: true
    show_line: false
    show_branch: false
    show_class_names: false
    only_changed_files: false
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
##[error]Found no pull request.
```

(It's a pull request and not a fork)

**Comment by hannseman** [comment]
On what triggers are the job run? Make sure that you use:
```
on:
  pull_request:
    branches:
      - master (or what ever you want to target)
```

If that's not possible you can limit the action with a conditional:
```
- name: Report coverage
  if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize')
  uses: 5monkeys/cobertura-action@master
  with:
    path: target/scala-2.12/coverage-report/cobertura.xml
    repo_token: ${{ secrets.GITHUB_TOKEN }}
    minimum_coverage: 90
```

**Comment by revmischa** [comment]
```
on: push
```
Is what I have for triggers

**Comment by hannseman** [comment]
Yes, that won't work. See my comment above. This action can only act on pull requests.

**Comment by lucasteles** [comment]
Why its only for PR? i'm having the same problem

**Comment by hannseman** [comment]
@lucasteles help me understand what your expected result is. The point of this action is to parse a cobertura report file and then write a comment on a PR with the content. If I’m missing a usecase I would love to know it but it’s hard to guess :)

**Comment by lucasteles** [comment]
@hannseman Hi, Now I saw how it works, the action puts a comment on PR, I didn't get it when i commented

Would be possible to add a note on workflow annotation?

![image](https://user-images.githubusercontent.com/3037609/82338948-dafe6900-99c3-11ea-8756-4ac536e7ba91.png)

**Comment by Siemian** [comment]
running this action on triggers different than pull request will be possible once this is merged https://github.com/5monkeys/cobertura-action/pull/20

**Comment by mskrip** [comment]
And if you want to have the PR number in a `push` event trigger you can do this, for example, through the Github API:

```yaml
    - name: Find a pull request containing this commit
      uses: octokit/request-action@v2.x
      id: get_pr
      with:
        route: GET /search/issues?q=${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set PR number
      run: |
        pr_number=${{ fromJson(steps.get_pr.outputs.data).items[0].number }}
        echo "PR_NUMBER=${pr_number}" >> $GITHUB_ENV
...
    - name: Post coverage report as comment
      uses: 5monkeys/cobertura-action@master
      with:
        ...
        pull_request_number: ${{ env.PR_NUMBER }}
```

It's not perfect but it gets the job done.

**Comment by dinko-pehar** [comment]
You can use:

```
...
pull_request_number: ${{ github.event.number }}
```

which makes finding Pull request and setting PR number obsolete.

**Comment by mskrip** [comment]
> You can use:
> 
> ```
> ...
> pull_request_number: ${{ github.event.number }}
> ```
> 
> which makes finding Pull request and setting PR number obsolete. Based on this [answer](https://stackoverflow.com/a/62436027/9871463).

This only applies if you are using `on: pull_request` unfortunately. `on: push` event trigger does not contain the event number.

**Comment by dinko-pehar** [comment]
`pull_request_number` refers to **pull_request** being open. If it's `on: push` trigger, where does this action post comment than ?

**Comment by paulz** [comment]
We got this working by using workflow triggered on push and PR but only running action on PR.
This way when PR updates report gets updated, but when we push on main without report is skipped.

```
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
...

    - name: cobertura-report
      uses: 5monkeys/cobertura-action@61b3b14d4da85a16843613a7de9c49aaeddd9d1b
      if: ${{ github.event_name == 'pull_request' }}
      with:
        path: html/cobertura.xml
        repo_token: ${{ github.token }}
        minimum_coverage: 100
        show_branch: true
        pull_request_number: ${{ github.pull_request.number }}
        fail_below_threshold: true

```

it seem extraneous to specify `pull_request_number: ${{ github.pull_request.number }}`
