### ISSUE TITLE
please make new release

### ISSUE THREAD

**Issue by paulz** [5monkeys/cobertura-action#48]
thank you for very useful action. it helps us to report branch coverage on PRs.

currently we have to use commit sha 61b3b14d4da85a16843613a7de9c49aaeddd9d1b because #46 not part of the latest release of v9: https://github.com/5monkeys/cobertura-action/releases/tag/v9
```
    - name: cobertura-report
      uses: 5monkeys/cobertura-action@61b3b14d4da85a16843613a7de9c49aaeddd9d1b
      if: ${{ github.event_name == 'pull_request' }}
      with:
        path: html/cobertura.xml
        repo_token: ${{ github.token }}
        minimum_coverage: 100
        show_branch: true
        pull_request_number: ${{ github.pull_request.number }}
        fail_below_threshold: true

```
