### ISSUE TITLE
Coverage always show 100%

### ISSUE THREAD

**Issue by Laki7877** [5monkeys/cobertura-action#51]
Hi

I'm trying to use thin action to help me generate coverage report. But when I see the bot comment on my Pull Request I always see it 100%

![CoverageTestReport](https://github.com/Laki7877/grails/raw/main/CoverageTestReport.png)

Here is my `coverage.xml`

https://raw.githubusercontent.com/Laki7877/grails/main/coverage.xml

and here is my action yaml examle

```
- name: Add coverage to PR
        id: cobertura
        uses: 5monkeys/cobertura-action@v9
        with:
          path: ${{ github.workspace }}/target/test-reports/cobertura/*.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 40
          skip_covered: false
          show_line: false
          show_branch: false
          show_class_names: true
          show_missing: true
          only_changed_files: false
```
