### ISSUE TITLE
Coverage report fails even with fail_below_threshold: false

### ISSUE THREAD

**Issue by SebastianBar** [5monkeys/cobertura-action#54]
It's currently failing even if you set `fail_below_threshold: false` 😢 (I know that's the default value, tried setting it manually anyways, but no luck). 

<img width="853" alt="Screen Shot 2021-11-03 at 12 22 41" src="https://user-images.githubusercontent.com/11593618/140090000-67c55022-7139-478e-b5f0-a399623b1f29.png">

**Comment by hannseman** [comment]
Weird! Are you sure that's the cause of the failure? Can you see any error message?

**Comment by SebastianBar** [comment]
Relates to https://github.com/5monkeys/cobertura-action/pull/46
CC @hannseman @kjagiello

**Comment by SebastianBar** [comment]
I guess so, I'll try setting it to v9 and try running the pipeline. Everything was fine until a few days ago.

**Comment by hannseman** [comment]
@SebastianBar can you paste the output from the failing action and the yaml-step for the action?

**Comment by SebastianBar** [comment]
@hannseman here's a screenshot of the coverage output (is properly posted as a comment within our PR's)
<img width="414" alt="Screen Shot 2021-11-03 at 12 30 37" src="https://user-images.githubusercontent.com/11593618/140091710-54e4121e-6b86-4b0e-9122-c23a2ff265ae.png">

The part for coverage report on our yaml:
```
- name: Report code coverage
        uses: 5monkeys/cobertura-action@master
        with:
          path: coverage/cobertura-coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
          only_changed_files: true
          minimum_coverage: 75
 ```
 
 That fails, as well as:
 ```
- name: Report code coverage
        uses: 5monkeys/cobertura-action@master
        with:
          path: coverage/cobertura-coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
          only_changed_files: true
          minimum_coverage: 75
          fail_below_threshold: false
 ```
 
 BTW, everything works as expected if I set the Action to `uses: 5monkeys/cobertura-action@v9`, so I guess that's the workaround for my org (for now).

  ```
- name: Report code coverage
        uses: 5monkeys/cobertura-action@v9
        with:
          path: coverage/cobertura-coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
          only_changed_files: true
          minimum_coverage: 75
 ```

I'm not able to share the entire yaml tho, sorry about that.
