### ISSUE TITLE
Error: Not Found

### ISSUE THREAD

**Issue by Asgaroth** [5monkeys/cobertura-action#64]
The action fails when running after a PR is merged. 

After a PR is merged to the main branch we trigger a workflow. I have unsuccessfully tried skipping the Cobertura action in that case because it fails with `Error: Not Found`

![Screen Shot 2021-12-13 at 4 09 38 PM](https://user-images.githubusercontent.com/755568/145889268-65e6a7c5-697b-49e8-bb35-40e7d7327576.png)

I am not sure exactly what is missing, it does perfectly on PRs

Relevant parts of the workflow

```
on:
  push:
    branches:
      - test/*
      - latest

  pull_request:
    branches:
      - latest
jobs:
  jest:
    needs: download-env
    runs-on: [self-hosted, linux, x64]

    steps:
      ... 
      - name: run unit tests
        run: npm run test-ci // > jest --ci --maxWorkers=2 --coverage --coverageReporters="cobertura"
      - name: coverage report
        uses: 5monkeys/cobertura-action@v12
        if: github.event_name == 'pull_request' && ${{ github.actor != 'dependabot[bot]' }}
        with:
          path: coverage/**/cobertura-coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          only_changed_files: true
          minimum_coverage: 40
          skip_covered: false
```

Output from `run unit tests`

```
Test Suites: 1 skipped, 110 passed, 110 of 111 total
Tests:       3 skipped, 582 passed, 585 total
Snapshots:   74 passed, 74 total
Time:        44.857 s
Ran all test suites.
📦 reporter is created on: /home/github/work/.../tmp/jest_html_reporters.html
```

Any ideas on how can I skip running this action after a merge? or what is it that the action is not finding?

Passing action during PR

![Screen Shot 2021-12-13 at 4 23 48 PM](https://user-images.githubusercontent.com/755568/145891080-ae722a4d-94ba-4582-a9ad-528641962883.png)
