### ISSUE TITLE
Not always posting comments

### ISSUE THREAD

**Issue by sdhull** [5monkeys/cobertura-action#71]
I've updated the trigger in hopes to get my workflow to run on `main` when PRs are merged (so using the `push` event) but the `pull_request` event for everything else:
```
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**/*'
```
You can see it's properly triggered on my pull request when I push new commits, with the `pull_request` event:
![image](https://user-images.githubusercontent.com/50039/171796469-9533897c-011d-4c94-a4f4-4f5fa8f36c98.png)

However it's not posting comments! The report says "updated 2 mins ago" so it seems like that's working properly but I'm not sure why it can't resolve the pull request number.

Is there some way to enable debug output or something like that?
Thanks!
