### ISSUE TITLE
Error: Resource not accessible by integratio

### ISSUE THREAD

**Issue by kkmann** [5monkeys/cobertura-action#80]
Hey,

cool action - still amazed by how complex it is to get coverage reporting into PRs withour external services...

Since a few days my pipelines fail with 

```
Error: Resource not accessible by integratio
```

see example: https://github.com/Boehringer-Ingelheim/oncomsm/actions/runs/4151027484/jobs/7201882375

Any ideas?

**Comment by itsalysialynn** [comment]
@kkmann I managed to fix this by giving the job `write-all` permissions:

```yml
jobs:
  quality-check:
    name: Quality Check
    permissions: write-all
```

**Comment by asteel-gsa** [comment]
> @kkmann I managed to fix this by giving the job `write-all` permissions:
> 
> ```yaml
> jobs:
>   quality-check:
>     name: Quality Check
>     permissions: write-all
> ```

This is also what worked for me, but, I would really like to see scoped permissions possible.
```yaml
jobs:
  job-name:
    permissions:
      pull-requests: write
```

**Comment by itzJustKranker** [comment]
you certainly don't need `permissions: write-all`. Although that would be the easiest fix. I believe I had to add `checks` and `issues` scopes for it to succeed. All in all my permissions look like this.

```yaml
permissions:
  actions: read
  contents: read
  packages: read
  pull-requests: write
  checks: write
  issues: write
```

but it would be great if the README, called out specifically what permissions the job required so we didn't have to guess
