### ISSUE TITLE
link missing files fails for windows action

### ISSUE THREAD

**Issue by wolframhaussig** [5monkeys/cobertura-action#86]
We integrated cobertura-action into a github action for .net on windows with the following config:
```
    - uses: 5monkeys/cobertura-action@master
      with:
        path: ./coverage/**/coverage.cobertura.xml
        skip_covered: false
        show_missing: true
        link_missing_lines: true
        link_missing_lines_source_dir: WinFormsThemes/WinFormsThemes
        minimum_coverage: 80
```
This works, but the links created by `link_missing_lines` are broken:
- Created Url: https://github.com/Assorted-Development/winforms-themes/blob/7791d2d43f639f670c95f8756c77a5766025401b/WinFormsThemes/WinFormsThemes/Themes\FileTheme.cs?plain=1#L104-L106
- Correct Url: https://github.com/Assorted-Development/winforms-themes/blob/7791d2d43f639f670c95f8756c77a5766025401b/WinFormsThemes/WinFormsThemes/Themes/FileTheme.cs?plain=1#L104-L106

The file seems to be reported as `Themes\FileTheme.cs` and is used directly in the created url instead of being translated into `/`.

An example can be found [here](https://github.com/Assorted-Development/winforms-themes/actions/runs/5694915808/job/15437192997)

Is this a bug or do I need to configure something else?
