### ISSUE TITLE
only_changed_files option not working

### ISSUE THREAD

**Issue by PascalArdex** [5monkeys/cobertura-action#88]
I have a dotnet / C# project using `5monkeys/cobertura-action@v13`, it works great with default values

Just tried to add the option `only_changed_files: true` as the project is getting bigger but it does not seem to have any effect.
More precisely, the report is still created but only shows the header line for **All files**
![Screenshot 2023-09-04 at 13-36-14 epona_ github_workflows at main · ardextech_epona](https://github.com/5monkeys/cobertura-action/assets/131418329/fe82a9dc-c78e-41e6-9302-ecebdbd2734b)

Here is an extract of my GitHub workflow
```
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Test
      run: dotnet test --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage"
    - name: Coverage Report
      uses: 5monkeys/cobertura-action@v13
      with:
        path: backend-api/tests/TestResults/*/*.xml
        minimum_coverage: 70
        skip_covered: false
        show_line: true
        show_branch: true
        show_class_names: false
        only_changed_files: true
```
