### ISSUE TITLE
Error: EACCES: permission denied, scandir '/lost+found'

### ISSUE THREAD

**Issue by paulmccarron** [5monkeys/cobertura-action#90]
Trying to generate a report for a dot net project, Action is failing with a permission error.

yml
```
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions: write-all
    defaults:
      run:
        working-directory: ./api
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=\"cobertura,opencover\" -p:ExcludeByFile=\"**/*.cshtml\" --no-build --verbosity normal Tests/*.Tests/
    - name: Test Code Coverage Comment
      uses: 5monkeys/cobertura-action@v13
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          path: /**/TestResults/coverage.cobertura.xml
          skip_covered: false
          minimum_coverage: 75
          show_line: true
          show_branch: true
          show_missing: true
          link_missing_lines: true
          link_missing_lines_source_dir: "api/"
          report_name: Api Test Coverage
```

Output
<img width="632" alt="Screenshot 2023-10-20 at 21 56 50" src="https://github.com/5monkeys/cobertura-action/assets/27147404/1629ed8f-f8ca-4bbe-927f-a11217b2ab4a">

**Comment by paulmccarron** [comment]
Fixed
Problem was the `/**/` in the `path` parameter, it seemed to be trying to read all the files in the `ubuntu-latest` runner. Updated to target xml file directly.
```
- name: Test Code Coverage Comment
      uses: 5monkeys/cobertura-action@v13
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          path: api/Tests/PROJECT_NAME.Tests/TestResults/coverage.cobertura.xml
          skip_covered: false
          minimum_coverage: 75
          show_line: true
          show_branch: true
          show_missing: true
          link_missing_lines: true
          link_missing_lines_source_dir: "api/"
          report_name: Api Test Coverage
```
